// File generated by FlutterFire CLI (cleaned manually).
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb6yMVOFaEBwbhRzCrM23YeSRMJCqBXmE',
    appId: '1:550470672896:web:5dceb67b85ebe64d022ee5',
    messagingSenderId: '550470672896',
    projectId: 'task-manager-app-3c310',
    authDomain: 'task-manager-app-3c310.firebaseapp.com',
    databaseURL: 'https://task-manager-app-3c310-default-rtdb.firebaseio.com',
    storageBucket: 'task-manager-app-3c310.firebasestorage.app',
    measurementId: 'G-3ZQ0JFM98R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfyBCjydr4J_iFGTTGd5Hkv45h-vvWyxM',
    appId: '1:550470672896:android:1f06d0ec7f997380022ee5',
    messagingSenderId: '550470672896',
    projectId: 'task-manager-app-3c310',
    databaseURL: 'https://task-manager-app-3c310-default-rtdb.firebaseio.com',
    storageBucket: 'task-manager-app-3c310.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb6yMVOFaEBwbhRzCrM23YeSRMJCqBXmE',
    appId: '1:550470672896:web:462c2cf8431de3e9022ee5',
    messagingSenderId: '550470672896',
    projectId: 'task-manager-app-3c310',
    authDomain: 'task-manager-app-3c310.firebaseapp.com',
    databaseURL: 'https://task-manager-app-3c310-default-rtdb.firebaseio.com',
    storageBucket: 'task-manager-app-3c310.firebasestorage.app',
    measurementId: 'G-1ET5E3ZHBF',
  );

}